# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: forbid-new-submodules
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: no-commit-to-branch  # blocks main commits.  To bypass do git commit --allow-empty
  # - id: pretty-format-json

# For more information about mypy, see https://github.com/pre-commit/mirrors-mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    exclude: ^(docs/|example-plugin/|tests/fixtures|tests/conftest.py)
    files: ^src/

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  # - id: pretty-format-toml
  #   args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: .copier-answer.yml

# For more information about YAPF, see https://github.com/google/yapf
- repo: https://github.com/craig8/mirrors-yapf
  rev: b84f670025671a341d0afd2b06b877b195d65c0f  # Use the sha / tag you want to point at
  hooks:
  - id: yapf
    name: yapf
    description: A formatter for Python files.
    entry: yapf
    language: python
    types: [python]

- repo: https://github.com/python-poetry/poetry
  rev: 1.2.2
  hooks:
  - id: poetry-check
